#!/bin/bash

# Checking that the domain was provided

: ${GITLAB_HOST:?"Set the environment variable GITLAB_HOST before running the script. (example: export GITLAB_HOST=registry.example.com"}
: ${MAIL_USERNAME:?"Set the environment variable MAIL_USERNAME before running the script. (example: export MAIL_USERNAME=user@example.com"}
: ${MAIL_PASSWORD:?"Set the environment variable MAIL_PASSWORD before running the script. (example: export MAIL_PASSWORD=my-mail-password"}

DOMAIN=$GITLAB_HOST
HEADER="Docker gitlab -"

echo "$HEADER in process..."

# Getting the docker-compose file

FILE="docker-compose.yml"
if [ -f "$FILE" ]
then
    echo "$HEADER docker-compose file was already downloaded."
else
    echo "$HEADER getting docker-compose file."
    wget https://raw.githubusercontent.com/beyond-coding/docker-gitlab/master/docker-compose.yml
    wget https://raw.githubusercontent.com/beyond-coding/docker-gitlab/master/docker-gitlab-runner.sh
    chmod 777 docker-gitlab-runner.sh
fi

# Generating the certificate

CERTIFICATE="certs/registry-auth.key"
if [ -f "$CERTIFICATE" ]
then
    echo "$HEADER Certificate ready, $CERTIFICATE already exists."
else
    mkdir certs && cd certs

    # certificate for GitLab
    # openssl req -nodes -newkey rsa:4096 -keyout registry.key -out registry.csr -subj "/CN=gitlab-issuer"
    # openssl x509 -in registry.csr -out registry.crt -req -signkey registry.key -days 3650

    # certificate for the Docker Registry
    openssl req -nodes -newkey rsa:4096 -keyout registry-auth.key -out registry-auth.csr -subj "/CN=$DOMAIN"
    openssl x509 -in registry-auth.csr -out registry-auth.crt -req -signkey registry-auth.key -days 3650

    cd ..

    # echo "Docker gitlab - SSL generation (lasting 10 years)"
    # echo "Docker gitlab - create the server private key"
    # openssl genrsa -out gitlab.key 2048
    # echo "Docker gitlab - create the certificate signing request (CSR)"
    # openssl req -new -key gitlab.key -out gitlab.csr
    # echo "Docker gitlab - sign the certificate using the private key and CSR"
    # openssl x509 -req -days 3650 -in gitlab.csr -signkey gitlab.key -out gitlab.crt
    # echo "Docker gitlab - strengthening the server security"
    # openssl dhparam -out dhparam.pem 2048

    # echo "Docker gitlab - installation of the SSL Certificates"

    # sudo mkdir -p /srv/docker/gitlab/gitlab/certs
    # sudo cp gitlab.key /srv/docker/gitlab/gitlab/certs/
    # sudo cp gitlab.crt /srv/docker/gitlab/gitlab/certs/
    # sudo cp dhparam.pem /srv/docker/gitlab/gitlab/certs/
    # sudo chmod 400 /srv/docker/gitlab/gitlab/certs/gitlab.key
fi

# Running services

echo "$HEADER running services"

docker-compose up -d

echo "$HEADER you can find GitLab at $DOMAIN:10080"
echo "$HEADER complete."


