#!/bin/bash

echo "Docker gitlab - in process..."

echo "Docker gitlab - get docker-compose file"

wget https://raw.githubusercontent.com/beyond-coding/docker-gitlab/master/docker-compose.yml

echo "Docker gitlab - in order to activate mail, edit SMTP_USER and SMTP_PASS"

echo "Docker gitlab - in order to run services run: docker-compose up -d"
